### ISSUE TITLE
Config option for cross-dimension-travel and the 8th and 9th chevron proposed by Dr.McKay on the Discord

### ISSUE THREAD

**Issue by Cinoxiiz** [MrJake222/AUNIS#153]
Addition of a config option for the cross-dimension-travel with the 8th and 9th chevron:
"Dr.McKay (24/04/2020 18:31)
@Mr. Jake could you add a config option for cross-dimension-travel and the 8th and 9th chevron because i dont want need 8 chevrons to travel inside the same solar and gate system
only if i change the gate system"

**Comment by PoltixeTheDerg** [comment]
Since there are multiple mods that add star systems it would be very difficult for AUNIS to tell what is inside or outside of the same galaxy and whatnot, and an 8 chevron address is for inter-galaxy address, not just for inter-gate-system travel. If a milky way and a pegasus gate were in the same galaxy it would still only take 7 chevrons to dial between them.

**Comment by MrJake222** [comment]
I can add JSON/XML with a list of arrays of dimension ID's that should be allowed to dial to each other with only 7 chevron. By default it would contain Nether and the Overworld.

**Comment by KamaroTheN7** [comment]
@MrJake222 I have a question, but I don't want to open new "issue", why addresses to nether and to overworld from there are standard 7 chevron one instead of 8 chevron inter dimension? I have also this weird screenshot... 
![2020-04-24_11 29 38](https://user-images.githubusercontent.com/55023705/80278232-e5934e80-86f4-11ea-9171-639726316dc0.png)
On left is regular generated Nether gate after using orlin gate, on right site I think its template (?) with gate that is unclickable and structure blocks.

**Comment by MrJake222** [comment]
Because Nether is dialable from Orlin's gate and is considered early game by me. And how did you get this screenshot? Next time ask on Discord

**Comment by KamaroTheN7** [comment]
> 
> 
> Because Nether is dialable from Orlin's gate and is considered early game by me. And how did you get this screenshot? Next time ask on Discord

I send message on discord.

**Comment by MrJake222** [comment]
Would adding a `group` string to the existing `aunis_dimensions.json` suffice?
