### ISSUE TITLE
crash bug with milky gates and universe dialer, easy to replicate. mod version 1.9.9 

### ISSUE THREAD

**Issue by Hyper-Tex** [MrJake222/AUNIS#206]
I was trying to get a nine symbol address to test the universe gates with 9 symbols. The dailer goes into the slot to copy the address into it's memory, but when it finishes, it crashes the world, and repeatedly crashes when trying to rejoin. I was able to replicate this four times with ease in four worlds.  I do not know if this is with just milky gates, or if it will do it for all gates, only tested it for milky gates with nine symbol symbol addresses.

**Comment by weberlepecheur** [comment]
I dont think so.
I think its because before you put the dialer in your inventory it has no nbt attached to it, but once its placed in it, there some nbt that generate on it and make appears "Gates saved : 0" a long with 2 others nbt.

Since you grab directly the item from JEI without getting those nbt its can cause a crash. That's what I think about the issue here.

**Comment by Berinkton** [comment]
The Universe dialer is supposed to be used with the Universe gates and not with the Milkyway or Pegasus gates. atleast according to the wiki entry. in earlier versions the gate wouldn't even try to write to the universe dialer.

**Comment by weberlepecheur** [comment]
It is now. We put the universe dialer in order to memorize the universe adress of the gate. That way we can call a milkyway gate from universe gate using the dialer.

**Comment by Berinkton** [comment]
But that is some sort of bug or is it not?! You need to put the Universe Crystal in to do that wich i think is not the authors intention.

**Comment by weberlepecheur** [comment]
This is normal, or else we won't be able to dial between milkyway and universe gate.
