### ISSUE TITLE
[Universe Gate] [OpenComputers] Gate won't dial per Computer

### ISSUE THREAD

**Issue by TheRedCreations** [MrJake222/AUNIS#260]
Aunis Version: aunis-1.12.2-1.9.12-alpha-2021-01-05

The Universe Gate won't dial per Computer. Milkyway Dialing is working.
![grafik](https://user-images.githubusercontent.com/35812887/103758244-385a2f80-5012-11eb-8adf-3729fc6fbffb.png)

**Comment by MrJake222** [comment]
Oh shit, It also affected OpenComputers... I've changed the `/sgsetaddress` command syntax to use for ex. 16 instead of G16. And it affected OC dialing also. I guess I'd have to support both format for the sake of compatibility (since it'd be easy to strip the G from the string). Thanks for the info ;)

**Comment by TheRedCreations** [comment]
I also tried only the id of the Glyph with same error.

**Comment by MrJake222** [comment]
Hmm, I'll look into it, thanks.
