### ISSUE TITLE
Holding Notebook page Crashes game.

### ISSUE THREAD

**Issue by LeePalmer2007** [MrJake222/AUNIS#6]
[crash-2019-06-29_22.24.07-client.txt](https://github.com/MrJake222/AUNIS/files/3342499/crash-2019-06-29_22.24.07-client.txt)

**Comment by Ep1cM1n10n** [comment]
[crash-2019-06-30_06.28.39-client.txt](https://github.com/MrJake222/AUNIS/files/3342591/crash-2019-06-30_06.28.39-client.txt)
After removing all the unnecessary mods and using a notebook page on a Stargate a few times, i can confirm that this bug is consistent, and after having another friend do the exact same and also crashing, this seems to be universal.

**Comment by MrJake222** [comment]
Notebook Page is not rendering now...

**Comment by MrJake222** [comment]
Not related, fixed in #7.
