### ISSUE TITLE
Orlin Gate crashes dedicated Server

### ISSUE THREAD

**Issue by RedstoneSucht** [MrJake222/AUNIS#97]
[crash-2020-03-30_10.12.32-server.txt](https://github.com/MrJake222/AUNIS/files/4402090/crash-2020-03-30_10.12.32-server.txt)
The Server crashed on creating a wormhole.

**Comment by MrJake222** [comment]
I think it's not Aunis mod causing the crash :thinking: Can you limit the mod list to minimum?

**Comment by 123mind123** [comment]
Well assuming it is a mod conflict and everyone who is having the same problem is caused by the same mod. I have cross referenced the mod list down to this:
[PossibleModList.txt](https://github.com/MrJake222/AUNIS/files/4405453/PossibleModList.txt)
If people have more crash txt files with the same problem I can shorten the list further.

**Comment by ShicKla** [comment]
I was having the same issue. It may seem like a mod conflict but it is not. The error is from the parsing of the dimension power map config. If the order of the listed dimensions in that file gets changed, it will fail to correctly find the nether dimension settings. Just deleting the file and having it generate a new file will also change the order of dimensions. 
To get a clean file I ended up creating a seperate and fresh minecraft installation and copied the config file from that.

**Comment by 123mind123** [comment]
Oh that interesting. Could I get a copy of the clean file from you?

**Comment by ShicKla** [comment]
I decided to take another look at the bug and found myself partly mistaken. It had nothing to do with the order of the entries in the aunis_dimensions.json file. The problem arises from an incorrect auto generated entry when there is no entry for the nether found.

Examples:
This is what it should be
```
"the_nether": {
    "energyToOpen": 3686400,
    "keepAlive": 1600
  }
```
This is what gets auto generated
```
"Nether": {
    "energyToOpen": 0,
    "keepAlive": 0
  }
```
So, to fix the problem just add the "the_nether" entry or change the "Nether" in the aunis_dimensions.json file.

@MrJake222 Correct me if I am wrong, I suspect the the ticking block entity error is getting thrown because the mod is getting stuck in a loop. When it reads the aunis_dimensions.json file and fails to find the entry for "the_nether" it creates a new entry and then reads the file again. Since the new entry being created is "Nether" and not "the_nether" it will always fail to find the correct entry, and keeps reading the file over and over. Thus creating the loop that Minecraft is catching and flagging as a ticking block entity.

**Comment by MrJake222** [comment]
No, it just crashes because it can't find a correct entry. But on pure Aunis setup it generates the file correctly(at least when I checked), so I'm wondering which mod causes it to generate wrong entry

**Comment by ShicKla** [comment]
I compared what mods I have installed to the ones that @RedstoneSucht, and went through each mod we have in common. It looks like Biomes O Plenty is causing the dimension rename, or at least in my case.
@MrJake222 I know its an obvious request, but can you confirm?

**Comment by RedstoneSucht** [comment]
OK. This issue is closed, cause the Modpack does not allow travel to a Stargate in the nether.(But to other Planets it works)

**Comment by MrJake222** [comment]
Confirmed. Aunis + Biomes O' Plenty crashes the game.
